apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enrober
  labels:
    name: enrober
spec:
  replicas: 1
  selector:
    matchLabels:
      name: enrober
  template:
    metadata:
      labels:
        name: enrober
        routable: "true"
      annotations:
        projectcalico.org/policy: "allow tcp from cidr 192.168.0.0/16; allow tcp from cidr 10.1.0.0/16"
        publicHosts: "ingress.apigee.com"
        publicPaths: "9000:/beeswax/deploy"
    spec:
      containers:
      - name: enrober
        image: jbowen/enrober:v0.1.2
        imagePullPolicy: Always
        env:
          - name: DEPLOY_STATE
            value: "PROD"
          - name: JWTTOKENIMPL
            value: "test"
        ports:
          - containerPort: 9000

